@startuml
start
:iterations = input();
:frame[51][51];
:a = {0,0}; 
:b = {50,0};
:c = {50,50};
:d = {0,50};

repeat
    :drawRect(a, b, c, d, frame);
    :a = middle(a,b);
    :b = middle(b,c);
    :c = middle(c,d);
    :d = middle(d,a);
    :interations = iterations - 1;
repeat while (interations != 0)

:exportFrame(frame);
stop
@enduml